### ISSUE TITLE
V11 - Could not load type 'TrafficManager.Traffic.Data.VehicleState' from assembly 'TrafficManager`

### ISSUE THREAD

**Issue by SevenQM** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#649] opened 2020-02-04 06:06 UTC
> # Solution
>   
> Unsubscribe / remove the following mods:
> * **CSUR_TMPE_Laneconnector_Fix**
> * **Advanced Junction Rule**
> ----

### Describe the problem
After the V11 update, I entered the game as before, and an error message popped up。
Could not load type 'TrafficManager.Traffic.Data.VehicleState' from assembly 'TrafficManager, Version=1.0.7026.40416, Culture=neutral, PublicKeyToken=null'. [System.TypeLoadException]

Details:
No details

I subscribed to the V11LABS version. No other subscriptions. There is no problem returning 10.20. Find solution: subscribe to V11 and subscribe to 10.20, the problem will only disappear when V11 is enabled

### Steps to reproduce

1. This error is caused by V11 update, no other modules are added
2. 
3. 

### Savegame?

https://steamcommunity.com/sharedfiles/filedetails/?id=1988175689

### Notes or questions?
[TMPE.log](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/4151649/TMPE.log)
[output_log.txt](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/4151651/output_log.txt)

**Comment by krzychu124** [comment] 2020-02-04 12:31
@SevenQM as I explained in comments on workshop item , it's the other mod which is dependent on TM:PE.

I suspect it's `CSUR_TMPE_Laneconnector_Fix` (it's obsolete, according to github page) or more likely `Advanced Junction Rule` Disable both for now if you want to use `v11` version and just wait for update.
 We can do nothing from our side. 

Tagging @pcfantasy

**Comment by pcfantasy** [comment] 2020-02-04 12:35
@SevenQM 

Both  CSUR_TMPE_Laneconnector_Fix and Advanced Junction Rule is obsolete.

CSUR_TMPE_Laneconnector_Fix is never published and it is for CSUR beta3. please use CSUR ToolBox in steam.

Advanced Junction Rule is removed from steam. Please delete it.

**Comment by aubergine10** [comment] 2020-02-04 15:49
@pcfantasy Can we incorporate that code (now in the CSUR ToolBox) direct in to TMPE? I assume it's to deal with lane connector issues on nodeless junctions? We have same issue for RWY (Railway) nodeless tracks and a few other networks too...

**Comment by pcfantasy** [comment] 2020-02-04 15:55
@aubergine10

Yes, in  CheckSegmentsTurningAngle, TMPE will check 

			if (turningAngle < 1f)
			{
.......................................
float dirDotProd = sourceDirection.x * targetDirection.x + sourceDirection.z * targetDirection.z;
				return dirDotProd < turningAngle;
}

if turningAngle < 1f  and dirDotProd > turningAngle; then return false to prevent some lane connectors.

Sometimes for some reasons, asset owner will create some roads which turningAngle is not 1f. So I just return true for all CSUR roads to allow all lane connectors.

**Comment by pcfantasy** [comment] 2020-02-04 15:59
@aubergine10 

Add codes
https://github.com/citiesskylines-csur/CSURToolBox/blob/master/CustomAI/NewLaneConnectorTool.cs

**Comment by aubergine10** [comment] 2020-02-04 16:00
@ kianzarrin Could you incorporate that in to the stuff you're doing with lane connectors?

**Comment by kianzarrin** [comment] 2020-02-05 19:31
@aubergine10 That review is already getting too big and out of hand.
I added fix for lane curves on the top of the ModeLaneMarker and SegmentLaneMarker stuff.

why not to do this in a separate pull request. It is not conflicting with my code.

**Comment by kianzarrin** [comment] 2020-02-08 12:25
I am on this. I will also fix CSUR toolbox.

**Comment by kianzarrin** [comment] 2020-02-08 12:27
Actually Ill just check for existence of :
```public static bool IsCSUR(NetInfo asset)```
using reflection or something.

**Comment by pcfantasy** [comment] 2020-02-08 12:30
@kianzarrin 

I suggest to return true for all roads.

Why do we need to check turningAngle to allow lane connector for road, only railway need this I think,

**Comment by kianzarrin** [comment] 2020-02-08 12:42
> @pcfantasy Sometimes for some reasons, asset owner will create some roads which turningAngle is not 1f. So I just return true for all CSUR roads to allow all lane connectors.

Can you please give me an example outside of CSUR?

**Comment by pcfantasy** [comment] 2020-02-08 12:43
@victoriacity

Can you help explain something about turningAngle?

**Comment by victoriacity** [comment] 2020-02-09 01:09
maxTurningAngle < 90 degrees is necessary for implementing continuous median toggled by traffic lights. For example, when traffic lights are turned off for a T-junction of CSUR roads, the median and markings on the straight road is not broken so that one does not have to plop medians and markings manually to achieve such effect as in vanilla roads. 

Specifically, the continuous median is a direct connect node triggered by a connect group (e.g., WideTram and NarrowTram), and most CSUR roads have connect group originally designed for trains and at-grade tram intersections. This leads to the need of setting an acute maxTurningAngle for continuous medians, because **the maxTurningAngle is the maximum angle by which the game tries to create direct connect nodes.**

![Screenshot 251](https://user-images.githubusercontent.com/14038064/74094328-11fbdf00-4aa5-11ea-82ce-0029f1fcfdcc.png)

In vanilla roads, the maxTurningAngle is 90°. This allows for making rail transit networks above or on the road turn at an intersection. In the screenshot above the turning angle of monorail is exactly 90° in the left and slightly larger than 90° in the right. Because the maxTurningAngle is 90°, the monorail is connected through a direct connect road only in the left.

![Screenshot 250](https://user-images.githubusercontent.com/14038064/74094381-dd3c5780-4aa5-11ea-85fe-06d50006af2f.png)

Therefore, if the maxTurningAngle=90 is used for continuous median (right road in the above screenshot), one obtains a similar effect as is expected for a monorail/tram intersection. However, in this case the desired effect is the median of the branched road comes to an end right before the intersection (left road in the above screenshot), and this has to be achieved by setting maxTurningAngle < 90. In CSUR roads, we set maxTurningAngle=75 (maxTurningAngleCos=0.2588) to allow for some flexibility in the intersection angle.

Outside of CSUR, the earliest road assets implementing continuous median also have maxTurningAngle < 90, for example:
https://steamcommunity.com/sharedfiles/filedetails/?id=1300747514
https://steamcommunity.com/sharedfiles/filedetails/?id=1327917624
https://steamcommunity.com/sharedfiles/filedetails/?id=1319965985

**Comment by kianzarrin** [comment] 2020-02-09 13:08
In the situation bellow its possible to select the monorail lanemarker even though it does not go anywhere.

![Screenshot (434)](https://user-images.githubusercontent.com/26344691/74102611-d36e2f00-4b4d-11ea-9357-e6fc8d9ab523.png) 

![Screenshot (433)](https://user-images.githubusercontent.com/26344691/74102609-cf421180-4b4d-11ea-912a-6214b02c4ad4.png)

**Comment by kianzarrin** [comment] 2020-02-09 13:43
OK I fixed the issue of the max turning angle. it only applies to tracks now:
![Screenshot (435)](https://user-images.githubusercontent.com/26344691/74103007-3a411780-4b51-11ea-93d4-dfe67c58fc93.png)
![Screenshot (437)](https://user-images.githubusercontent.com/26344691/74103009-3e6d3500-4b51-11ea-971c-4d49a8ecb48e.png)

**Comment by kianzarrin** [comment] 2020-02-09 14:03
To solve https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/issues/649#issuecomment-583843474 I made exception for unconnected tracks:
![Screenshot (439)](https://user-images.githubusercontent.com/26344691/74103482-f3edb780-4b54-11ea-9e68-a5c52daafc88.png)
![Screenshot (440)](https://user-images.githubusercontent.com/26344691/74103487-f819d500-4b54-11ea-8217-81ef59e1d836.png)

**Comment by kianzarrin** [comment] 2020-02-09 14:05
The TMPE side is fixed(shortly will put a pull request)
the CSUR should not patch TMPE if the fix is present. One way to do this is to check for TMPE version:
```
TrafficManagerMod::public const string VERSION = "11.0";
```
Can I rely on this to be   `VERSION >= 11.1`

**Comment by pcfantasy** [comment] 2020-02-09 14:15
@kianzarrin 

OK，I will update this too.

**Comment by aubergine10** [comment] 2020-02-09 14:40
I think the `VERSION` needs to be string due to CO API (`IUserMod`) - could be wrong, been ages since I checked.

**Comment by aubergine10** [comment] 2020-02-09 15:17
Just realised `VERSION` isn't part of `IUserMod` so we can change it to any format we want

@kianzarrin Change it to number but provide some way to include string bolt ons in the stuff that gets shown to user (eg. `11.1-beta1` or `11.0-hotfix`)

**Comment by kianzarrin** [comment] 2020-02-09 19:09
@aubergine10 
>Just realised VERSION isn't part of IUserMod so we can change it to any format we want
@kianzarrin Change it to number but provide some way to include string bolt ons in the stuff that gets shown to user (eg. 11.1-beta1 or 11.0-hotfix)

I prefer to use Version class. 
```c#
// usage example
new Version(11.1,blah,blah)
version.ToString(2) //major and minor only
version1 > version2 // it has internal comparison
```

And I will get `Version` from AssemblyInfo.cs:
```C#
       public static string VersionString => ModVersion.ToString(2);
       public static Version ModVersion => typeof(TrafficManagerMod).Assembly.GetName().Version;
```

Hopefully no one has used `TrafficManagerMod::VERSION` externally.

**Comment by kianzarrin** [comment] 2020-02-10 00:07
I fixed this issue: The images bellow are produced while CSUR did not patch TMPE.
![Screenshot (445)](https://user-images.githubusercontent.com/26344691/74113006-0d6d1e80-4baa-11ea-997d-4461ab3b0a20.png)

![Screenshot (444)](https://user-images.githubusercontent.com/26344691/74113004-08a86a80-4baa-11ea-967f-bebae0dcabee.png)

**Comment by kianzarrin** [comment] 2020-02-10 00:47
detecting median is not part of this issue but rather its part of #243
![Screenshot (448)](https://user-images.githubusercontent.com/26344691/74113845-75723380-4baf-11ea-86b3-a7e50d73f462.png)

**Comment by aubergine10** [comment] 2020-02-10 17:29
A beta is being pushed to LABS page that does not yet contian CSUR fix. The beta will be versioned `11.1.0` (note: build value)

The CSUR update will be in next beta, version 11.1.1. For more details see #687

**Comment by aubergine10** [comment] 2020-02-12 05:40
@SevenQM Please let us know if the issue is fixed or not.

**Closed** 2020-02-16 08:10 UTC
Labels: EXTERNAL, awaiting feedback, out of scope
