### ISSUE TITLE
Lost Customizations, Trapped on LABS

### ISSUE THREAD

**Issue by shinzon76** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#209] opened 2019-03-04 04:58 UTC
I switched to Krzychu1245's TPME with version 1.10.14 from linuxfan's original. Linuxfan's TPME was unsubscribed. Currently using latest version 1.10.16.

Upon starting Cities Skylines and loading my save, I noticed that all of my customizations--lane selections, traffics arrows, speed limits, etc-- had disappeared. Tried uninstalling and reinstalling the mod, tried verifying the game cache, but the customizations do not return. 

Fortunately, the corruption/dataloss seems to be limited to that particular save file, and I was able to backtrack to an earlier save with all customizations intact, and only a few hours of progression lost.

Also,  I encountered another problem: since Krzychu1245's TPME is now an unstable branch, I attempted to switch back to the stable version of TMPE, unsubscribing from LABS, but when I load a save file with the stable version, all of my customizations are gone.  If i unsubscribe from latest stable and resubscribe to latest LABS, my customizations on the save file return. 

Any suggestions on what can be done? Files/logs can be provided on request.

**Comment by aubergine10** [comment] 2019-03-04 16:27
Thanks for the report @shinzon76 

For now keep using Labs version. It's currently 'stable' but a few versions ahead of the LinuxFan version of the mod. We are working to get the LinuxFan version up to 1.10.16 as soon as possible.

**Comment by aubergine10** [comment] 2019-03-04 17:27
Tagging #210 and #208

**Comment by VictorPhilipp** [comment] 2019-03-04 22:11
Duplicate of #208

**Comment by aubergine10** [comment] 2019-03-04 23:02
Closing as duplicate.

@shinzon76: You can follow progress via the other ticket, #208.

**Closed by aubergine10** 2019-03-04 23:02 UTC
Labels: STABLE, bug, confirmed
