### ISSUE TITLE
Incompatible Detector Should Not Warn When Not Enabled

### ISSUE THREAD

**Issue by FireController1847** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#284] opened 2019-04-14 23:15 UTC
As much as I enjoy this new incompatible mod thing, it's annoying when I'm subscribed to a mod for testing purposes and, even if the mod's not enabled, it will warn me that TM:PE won't work with it anyways. TM:PE should warn me in the follow situations:

- If the state of TM:PE is toggled (on or off) ONLY for enabled mods.
- If the incompatible mod is enabled.

At least, this is my opinion.

**Comment by aubergine10** [comment] 2019-04-14 23:19
Duplicate of #264 

?

**Comment by aubergine10** [comment] 2019-04-14 23:20
Related to (or could be combined with) #264

**Comment by FireController1847** [comment] 2019-04-14 23:20
@aubergine10 Similar but not the same; I don't want to _disable_ the detector, I just only want it to detect ENABLED mods

**Comment by aubergine10** [comment] 2019-04-20 14:28
@FireController1847 Please check the linked pull request #286 and confirm if it's working correctly.

**Closed** 2019-04-20 19:08 UTC
Labels: UI, enhancement, usability
