### ISSUE TITLE
Automatically place speed limit signs

### ISSUE THREAD

**Issue by VictorPhilipp** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#159] opened 2019-03-03 04:09 UTC
Place automatically speed limit signs, when the maximum speed changes.

https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/118

**Comment by VictorPhilipp** [comment] 2019-03-03 04:09
Someone would have to create sign props since I don't know how to do this.

**Comment by VictorPhilipp** [comment] 2019-03-03 04:09
Can of worms.

First, I often tweak speeds for visual effect:

* At a sharp bend, I want my vehicles to slow down
* I slow steep uphill lanes so in comparison the downhill lanes look faster
* I slow train tracks in train stations so trains passing through station slow a little

I wouldn't want speed sign chaos in any of these situations. For example, at a sharp turn I put a "sharp bend ahead" sign, not a speed sign.

As for updating signs, there are mods for removing them and there are mods for creating customisable signs. Different countries have different sign styles - completely outside scope of TP:ME IMO.

**Comment by aubergine10** [comment] 2019-03-03 04:40
Duplicate of #49

**Closed by aubergine10** 2019-03-03 04:40 UTC
Labels: duplicate, feature, help wanted
