### ISSUE TITLE
Improve persistency of lane connections, speed limits, vehicle restrictions

### ISSUE THREAD

**Issue by VictorPhilipp** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#160] opened 2019-03-03 04:11 UTC
Monarch:
"Would it be possible to make the Lane connector persistent when using road upgrade tool to a road with same number of connection points and/or using the "Zoning toolset (toggle + upgrade tool)" mod to toggle zoning?

Also if Parking/Vehicle restrictions and Speed limits could be persistent it would be nice!"

https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/122

**Comment by VictorPhilipp** [comment] 2019-03-03 04:11
If it's not possible to make it consistent, could some sort of visual cue (or sound?) be provided to let user know the action they are about to take (eg. upgrade road) will have impact on the TM:PE config for the segment or junction?

**Comment by aubergine10** [comment] 2019-03-03 04:37
Duplicate of #43

**Closed by aubergine10** 2019-03-03 04:37 UTC
Labels: duplicate, enhancement
