### ISSUE TITLE
Regular vehicles can get out of the way for emergency vehicles

### ISSUE THREAD

**Issue by VictorPhilipp** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#152] opened 2019-03-03 03:57 UTC
Bokker12: "I see that emergency cars stop for other cars at junctions, roundabounds etc. can you mod your mod that ai cars go to the side if there is an emergency car comming up? I know this is a job what is pretty hard I guess, but I'd like to know your answer if you are gonna do that or try it?"

https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/97

**Comment by aubergine10** [comment] 2019-03-03 04:43
Duplicate of #64

**Closed by aubergine10** 2019-03-03 04:43 UTC
Labels: duplicate, feature
