### ISSUE TITLE
Feature request: Lane reverse button

### ISSUE THREAD

**Issue by VictorPhilipp** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#203] opened 2019-03-03 05:17 UTC
Hey. Not sure where else to make this plus seen others do it. Apologies if this is improper.

First, I'm not entirely sure whether this is possible. If it isn't, I apologise again. I'm not very familiar with how mods interact with roads or whether they can do what I'm thinking.

In short: I would like a button which would allow me to reverse the direction of traffic on a per-lane basis.

I expect it's a very low priority request considering it hasn't been requested before (as far as I'm aware) and may not be entirely possible, especially since you likely have other bugs and features to add which are more pressing than this.

I think this would be most useful during evacuations where traffic often gets backed up on some roads (not due to bad design, but due to unexpected quantity), but also where people just want to close a lane or segment of a lane for visual appeal in imagery.

https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/229

**Comment by VictorPhilipp** [comment] 2019-03-03 05:17
There are some modern intersections that reverse the direction of some lanes to reduce number of conflict points (merge/diverge/crossing) of traffic flowing over the junction: https://www.citylab.com/solutions/2013/01/could-these-crazy-intersections-make-us-safer/4467/

There are also contraflow lanes, for example to bypass roadworks or emergency evacuation: https://en.wikipedia.org/wiki/Contraflow_lane_reversal

Currently there doesn't seem to be a way to create such roads in the game, so having lane reverse tool would be great.

**Comment by VictorPhilipp** [comment] 2019-03-03 05:17
This is super hard to do because we would have to modify a ton of code. I think it would be easier to create reversed road assets.

**Comment by VictorPhilipp** [comment] 2019-03-03 05:17
The intention of the request was primarily to avoid replacing roads as this causes issues with lane connections and restrictions, custom speed limits, parking settings, zoning (when it has been disabled around the road), and some other things too. The preference being that the lane direction for each individual lane could be toggled as-needed for traffic flow. A 3+3 avenue could be converted on-demand to a 2+4 without replacing the physical asset.

**Comment by aubergine10** [comment] 2019-03-03 05:18
This is essentially a duplicate of #122 (tidal lanes).

**Closed by aubergine10** 2019-03-03 05:18 UTC
Labels: duplicate, out of scope
