### ISSUE TITLE
Wait to fill cargo trains/trucks/ships more

### ISSUE THREAD

**Issue by VictorPhilipp** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#170] opened 2019-03-03 04:23 UTC
> # Solution:
>  
> Use the [Cargo Hold Fix](https://steamcommunity.com/sharedfiles/filedetails/?id=1721492498) mod to make cargo vehicles (trains, trucks, ships, planes) wait longer to fill up more.

Phoenix C64 says:
"I know this mod is more about traffic related to roads... but I know it also affects trains to some degree as I had to turn off TMPE at one point because it was affecting my trains in some bad way. (spend 3h. trouble shooting the problem and disabling TMPE fixed the issue)

Now, I currently have a big complaint about trains: trains only take 1-2 cargo trucks as a load and bottleneck my train network with 7-13% filled trains.

Could TMPE have an option so trains don't spawn until they have an X% of load (let's say 50%)"

https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/136

**Comment by VictorPhilipp** [comment] 2019-03-03 04:23
Quite some times i observe the same effect with cargo ships and trucks (especially when i upgraded the capacity of trucks using AVO :-))

**Comment by VictorPhilipp** [comment] 2019-03-03 04:23
From a related issue: #123 

> 1. Fix that cargo trains drive with around with really low loads of cargo. (1 - 30 %)
> 2. Automatically select appropriate vehicle for load --> a van for a small load, a truck for a large load. (i've made difference in capacity in AVO, sadly i get trucks loaded for 50%, instead of a van, loaded for 100%), while vans would probably mean faster delivery.

**Comment by aubergine10** [comment] 2019-03-03 04:29
Would this be better placed in a different mod?

Recently there was an industries fix mod in workshop that did something like this but for cargo trucks, maybe that could be better home (or a branch of it)? This was the mod (I haven't tested what it does exactly): https://steamcommunity.com/sharedfiles/filedetails/?id=1562650024

**Comment by aubergine10** [comment] 2019-03-03 04:34
Duplicate of #161

**Comment by aubergine10** [comment] 2019-04-04 20:18
Boformer just discovered this in the code and it seems to be reason trains are mostly empty:

![unknown](https://user-images.githubusercontent.com/1386719/55585597-f6a2a380-571e-11e9-9e7f-09bb30ca0a98.png)

> `CargoTrainAI simulationstep`
> When counter is `255` train will spawn and leave outside connection
> Counter is counted up when `flag` is `false`. `flag` is set randomly, 1:1 chance
> Decrease the chance that `flag` is `false` = trains will wait a bit longer

**Comment by aubergine10** [comment] 2019-04-04 20:21
Tagging #180 (the closed #161 was referenced by it)

**Comment by boformer** [comment] 2019-04-04 20:46
In my opinion this has nothing to do with TM:PE, should be a separate mod. It affects every player, even those who do not want TM:PE.

**Comment by aubergine10** [comment] 2019-04-06 00:02
Quboid produced this very beta (dev build) mod to make cargo trucks/trains/ships wait 10x longer before departing (note: also disables dummy traffic to make testing easier on the eye; also _heavy_ log spam with debug infos) 

[CargoHoldFix.zip](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3049961/CargoHoldFix.zip)

Not for general release but there if anyone wants to test & give feedback.

Once it's on general release I'll update OP with a link to workshop and close this issue.

**Comment by aubergine10** [comment] 2019-04-06 12:21
Updated cargo mod for testing

> **Quboid:** now has an options page, optional dummy-traffic killing, less spam

[CargoHoldFix-20190406.zip](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3050444/CargoHoldFix-20190406.zip)

**Comment by aubergine10** [comment] 2019-04-08 01:21
Latest beta from Quboid

[CargoHoldFix-20190407.zip](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3052297/CargoHoldFix-20190407.zip)

**Comment by aubergine10** [comment] 2019-04-23 18:32
The mod is now released to Steam workshop:

https://steamcommunity.com/sharedfiles/filedetails/?id=1721492498

**Closed by aubergine10** 2019-04-23 18:32 UTC
Labels: EXTERNAL, discussion, out of scope
