### ISSUE TITLE
Change default traffic light behaviour

### ISSUE THREAD

**Issue by VictorPhilipp** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#193] opened 2019-03-03 04:59 UTC
I think the main reason is why we need to setup timed traffic lights is because the default traffic light settings are a bit wack, as they allow multiple directions to enter intersection at the same time, causing collision points. It would be more logical if the default setting would not do that, and that way we can reserve the timed traffic lights for the more complex situations.

So for the default traffic lights it would be more logical to set up as:
Lanes can go straight, left and right from one direction, the lane to the left can also turn at the same time because traffic won't hit each other.
In addition add a step where pedestrian can pass, without being hit by cars.

This setup might be more logical as default traffic light setup.

https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/200

**Comment by VictorPhilipp** [comment] 2019-03-03 04:59
A relevant bit of information on behaviour I've noticed in-game regarding lane arrows (and the behaviour of what left/right is on a traffic light, is that sometimes "left" or "right" also goes what you would expect to call "forward". Visual example as follows.

This is an intersection in my city of 163k, and it's pretty busy:
![image](https://user-images.githubusercontent.com/39814064/42945719-03ac8b3e-8b61-11e8-9bca-deba6d0a683e.png)

On the 2by3 median-divided avenue going upwards, there's an `LeftForward Right Right` lane arrow system which I put in place. On that particular part of the road , "right" is any path drawn by a yellow line whereas Forward is identified by the green lines. It cuts off traffic coming from lanes intersection with the red arrows, as well as traffic coming from the other side.

I do agree with the step where pedestrians can pass without being hit though. More often than not traffic is moving slowly through non-timed lights because of pedestrians crossing all of the time.

**Comment by VictorPhilipp** [comment] 2019-03-03 04:59
What you're essentially after is a "default" traffic light setup that minimises crossing conflict points and also provides safe points for pedestrians to cross. So essentially it's a mathematical reduction of things like this:

![conflict-points-of-a-typical-two-lane-four-way-intersection-or-driveway-sudas](https://user-images.githubusercontent.com/1386719/43047196-920f2488-8dcb-11e8-8c52-62fc56500e79.png)

Ultimately, the player should be designing their roads so as to reduce crossing and merging points wherever possible.

I'll create separate issue requesting tool for visualising crossing/merging/diverging points as that in itself would be incredibly useful.

**Comment by aubergine10** [comment] 2019-03-03 05:12
Duplicate of #5

**Closed by aubergine10** 2019-03-03 05:12 UTC
Labels: duplicate
