### ISSUE TITLE
Yielding vehicles can semi-enter the junction

### ISSUE THREAD

**Issue by VictorPhilipp** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#140] opened 2019-03-03 03:38 UTC
"Totally love this mod! It's pretty much half the reason why I keep playing this game. I was thinking of ways this mod could further improve motor vehicle traffic simulation in the game.
Would it be possible to have a feature where at traffic lights with unprotected left turns (green circles), cars attempting to turn left will yield to oncoming traffic, waiting in the middle of the box until either:
1) The car finds a gap in oncoming traffic
2) Oncoming traffic gets backed up and jammed, leaving the car free to turn through
3) The light turns red, and all left-turning cars that are inside the box are free to clear the intersection
?

Essentially, I want the game's vehicles to turn left as similarly to this style as possible:
[Video]
Like and share this video about understanding traffic signals and help educate others who are unsure about this basic traffic signal function and safety.

I remember a very long time ago (more than a year?) some previous version of the traffic manager mod made it so that at intersections with user-made timed traffic lights, left-turning traffic would wait behind the line until oncoming traffic cleared. This was a good idea in principle, but because left-turning traffic waited so conservatively, this caused major backups at intersections without green arrows. I was wondering if you could revamp this old feature, and find some middle ground between the "granny" drivers of the old mod (almost never turning left) and the current vanilla game, where left-turning drivers simply throw themselves into oncoming traffic, getting stuck in a knot of cars. By having left-turning cars pull into the intersection a little bit while they wait, more vehicles can cycle through the traffic light, since the vanilla game currently allows for vehicles within the box to finish proceeding through the intersection even after the light turns red.

I think that this feature, if successful, would be a great addition to your mod. While the timed traffic light feature is great for the city's busiest intersections, it would be cumbersome to have to set up, adjust the turning lanes and timings for every junction in the city. I understand that because of the wide variety of angles that intersections can be built, it can be difficult to do this. Nonetheless, having a feature of this mod where by the push of a button, enabling this city-wide driving practice of waiting in the middle of the box to turn left and going upon the light turning red would be an excellent way to improve traffic flow in people's cities as well as improve realism, since this is how people in major cities turn left at unprotected green lights. Let me know what you think about this idea, and please look into it, since I believe this would a nice little touch to the game's traffic simulation that would also have practical benefits and realism, and a variation of it seems to have been done before to (some) extent (I think?) in Traffic Manager. Is this a feasible suggestion? Could it be implemented in the next version?
Once again, thank you for putting your talents toward helping this community. "

see http://steamcommunity.com/workshop/filedetails/discussion/583429740/1290690669222931967/

https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/62

**Comment by VictorPhilipp** [comment] 2019-03-03 03:38
There's a simple fix for this issue: Just disable the "priority rules at traffic lights" at the last second before the traffic light turns red.

**Comment by aubergine10** [comment] 2019-03-03 05:01
Also, not sure about the issue references shown above - copy/paste issues from old repo?

This seems to be duplicate of #46

**Closed** 2019-03-03 06:04 UTC
Labels: duplicate, feature
