### ISSUE TITLE
Default road speeds vs. monorail roads

### ISSUE THREAD

**Issue by VictorPhilipp** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#187] opened 2019-03-03 04:50 UTC
When setting default speeds for roads (lane speeds tool > default speeds), a road with embedded monorail shows 100km/h.

I assume setting that road to 50km/h (because I want all my small roads to be ~30mph) would cause the monorail to also become 50km/h?

Furthermore, is this issue also affecting roads with bike lanes (does bike lane get set to 50km/h if I set the default speed for the road it's part of to 50km/h)?

I imagine setting speeds for individual lanes in defaults panel isn't going to happen (because a segment of the road would somehow need rendering in the dialog window = pain). As such, when setting speed for a prefab that contains road vehicles, could it ignore the embedded monorail/train/tram tracks? Furthermore, if I set the speed for the stand-alone monorail tracks (those that are not part of a road vehicle network), could that speed affect all monorails that are part of a road network? Same sort of thing with rail, tram, etc.

https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/181

Example, I set default speed of a 2 lane road + monorail to 50km/h. Only the 'road' parts of that prefab are set to 50km/h, the monorail part is not affected. Then I set the 'standalone' monorail prefab to 110km/h - this sets all the monorails to that speed, including those embedded in roads.

Related issue: #131

**Comment by aubergine10** [comment] 2019-03-03 04:53
Duplicate of #84

**Closed by aubergine10** 2019-03-03 04:53 UTC
Labels: duplicate, enhancement
