### ISSUE TITLE
Add seperate traffic lights for bicycles

### ISSUE THREAD

**Issue by VictorPhilipp** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#153] opened 2019-03-03 03:58 UTC
@Seanster requests adding traffic lights for bicycles.
http://steamcommunity.com/workshop/filedetails/discussion/583429740/1479856439043368970/

https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/102

**Comment by VictorPhilipp** [comment] 2019-03-03 03:58
Chiming in to say I'd love this too! Vital for making realistic lights at junctions with roads that have bike tracks/lanes and bike paths as well. Common in the Netherlands and many other countries, and especially important for separating peds/cars from bikes for safety :)

**Comment by aubergine10** [comment] 2019-03-03 04:42
Duplicate of #18

**Closed by aubergine10** 2019-03-03 04:42 UTC
Labels: duplicate, feature
