### ISSUE TITLE
MPH vs KPH 

### ISSUE THREAD

**Issue by VictorPhilipp** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#139] opened 2019-03-03 03:37 UTC
"Is there an option to use MPH instead of the default KPH, along with the corresponding icons?"

see http://steamcommunity.com/workshop/filedetails/discussion/583429740/142261027571919093/

https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/61

**Comment by VictorPhilipp** [comment] 2019-03-03 03:37
Adding my vote to this. I recently realised that all my "30" roads are actually 30 KMH which works out at ~19 MPH

No wonder my traffic was going so slow!

**Comment by aubergine10** [comment] 2019-03-03 04:55
Duplicate of #13

**Closed by aubergine10** 2019-03-03 04:55 UTC
Labels: duplicate, feature
