### ISSUE TITLE
Suggestion: use parking lane free spots to let emergency vehicles override

### ISSUE THREAD

**Issue by VictorPhilipp** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#201] opened 2019-03-03 05:12 UTC
When a non-emergency vehicle gets aware of an emergency vehicle behind (in emergency mode ofc), try to go to a free spot of a parking lane if available nearby, let the emergency vehicle pass by and continue on the road.

**Comment by VictorPhilipp** [comment] 2019-03-03 05:12
👍

**Comment by aubergine10** [comment] 2019-03-03 05:13
Already working on this :)

Duplicate of #64

**Closed by aubergine10** 2019-03-03 05:13 UTC
Labels: duplicate
