### ISSUE TITLE
Tool to render crossing, merging and diverging points

### ISSUE THREAD

**Issue by VictorPhilipp** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#197] opened 2019-03-03 05:06 UTC
Conflict points play a pivotal role in good road design, yet there's no way to visualise them in game.

![fig8](https://user-images.githubusercontent.com/1386719/43047219-f8c542d4-8dcb-11e8-890f-dd2f6516a045.jpg)

The points could be rendered with shape overlays on the roads?

![conflict-points-of-a-typical-two-lane-four-way-intersection-or-driveway-sudas](https://user-images.githubusercontent.com/1386719/43047232-2011666a-8dcc-11e8-92c3-1a29229c0066.png)

![fig017a](https://user-images.githubusercontent.com/1386719/43047238-2869a2d2-8dcc-11e8-8a74-8b7ec76ea9a3.gif)

At junctions, it would be extremely awesome if weighted scores could be shown - maybe clicking junction could show something akin to this:

![images-1](https://user-images.githubusercontent.com/1386719/43047249-50b6aaf0-8dcc-11e8-92e8-faf51c5828d1.png) ![images](https://user-images.githubusercontent.com/1386719/43047250-50cee214-8dcc-11e8-9ceb-2cefebae1127.png)

The feature would help with creating more effective road networks, it would help guide implementation of better default traffic lights (
https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/200) and would be extremely useful when creating custom traffic lights (
https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/143).

https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/210

**Comment by VictorPhilipp** [comment] 2019-03-03 05:06
Would definitely be helpful but I give up on those kind of overlay visualizations.

**Comment by VictorPhilipp** [comment] 2019-03-03 05:06
It's something that's being worked towards on the @krzychu124 branch.

**Comment by aubergine10** [comment] 2019-03-03 05:10
Duplicate of #4

**Closed by aubergine10** 2019-03-03 05:10 UTC
Labels: duplicate
