### ISSUE TITLE
Cars disappearing after road/rails chaning

### ISSUE THREAD

**Issue by VictorPhilipp** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#205] opened 2019-03-03 05:20 UTC
When I modify a road or a rail, every vehicle disappears at this point 

also mentioned here: https://steamcommunity.com/workshop/filedetails/discussion/583429740/1748980761804012244/

As it seems the display where you can see where routes beginn and where they end ... all routes end a the modified road/rail.

Can you please fix it ... or which informations can I provide for helping you

https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/236

**Comment by VictorPhilipp** [comment] 2019-03-03 05:20
We're investigating this in new fork of the mod (see reference links above). If you could provide any additional infos in those links, where applicable, it would be most useful.

**Comment by aubergine10** [comment] 2019-03-03 05:54
Duplicate of https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/issues/86 (fixed, hopefully, in 1.10.16  release).

**Closed by aubergine10** 2019-03-03 05:54 UTC
Labels: duplicate
