### ISSUE TITLE
Delete/upgrade a road and vehicles despawn rather than reroute

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#86] opened 2019-02-15 16:34 UTC
> chris_852
> Broke my game. Once I deleted roads and rebuild them, traffic would disappear once it got to the newly constructed road segments. After I removed this mod, traffic returned to normal.

What should happen: Traffic reaching the point where road was deleted should reroute (ideally deleting roa should cause rerouting for any traffic destined for that road)

# Temporary workaround

Current advice to end users: Wait a few minutes and traffic should return to normal

See: [Troubleshooting guide](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Bulldozing-road-causes-vehicles-to-despawn-nearby)

**Comment by aubergine10** [comment] 2019-02-15 20:50
I've confirmed this bug.

Steps to reproduce:

1. Start new map
2. Build a square-shaped zoneable road
3. Zone a bunch of residential, etc
4. When cars start showing up regularly, delete a chunk of road

What happens:

* Cars and trucks were despawning upon reaching the end of the road
* Service vehicles seemed to survive and did u-turn at end of road

What should happen:

* Cars and trucks should u-turn at the end of the road

Mod settings:

* Simulation accuracy: Very high
* Reckless drivers: 0%
* Realistic speeds
* Busses may ignore lane arrows
* Ban private cars and trucks on bus lanes
* Enable highway specific lane merging/splitting rules
* Heavy vehicles prefer outer lanes on highways
* Evacuation busses may ignore traffic rules
* All features enabled on maintenance tab
* No other options selected (except those above) in mod settings

**Comment by aubergine10** [comment] 2019-02-15 21:14
After a few seconds, vehicles did start re-routing (they did u-turns at end of road; cars and trucks tested)

However, when I replaced road, vehicles still did u-turns in the same place (cars and trucks tested).

A while later, they started using road normally again.

Seems vehicles affected by changes to road aren't being updated as soon as expected. They seem to be lagging behind. When road is first removed, that lag is causing cars (possibly also trucks, will test) to despawn.

**Comment by aubergine10** [comment] 2019-02-15 21:31
Pedestrians and service vehicles seem to be repathing fast, other vehicle types (including trucks) lag by a few seconds.

I tried changing mod options (eg. disabling the things I had selected from above, setting sim accuracy to very low, vehicle restriction aggression to low) but it made no difference.

Image of my test setup below:
![testing](https://user-images.githubusercontent.com/1386719/52885404-fe0aef00-3168-11e9-9dd0-b7130e4bbbf3.gif)

**Comment by aubergine10** [comment] 2019-02-15 23:36
# Temporary workaround

Current advice to end users: Wait a few minutes and traffic should return to normal

See: [Troubleshooting guide](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Bulldozing-road-causes-vehicles-to-despawn-nearby)

**Comment by aubergine10** [comment] 2019-02-16 14:58
Tagging https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/236

**Comment by aubergine10** [comment] 2019-02-16 15:02
Related discussion on Steam - note the date, I think this issue could possibly be due to changes in the old TMPE around that time so we might be able to track it down to a commit?

https://steamcommunity.com/workshop/filedetails/discussion/583429740/1748980761804012244/

**Comment by aubergine10** [comment] 2019-02-18 00:13
Just had another similar report on Steam - it also happens when roads are updated.

**Comment by aubergine10** [comment] 2019-02-18 16:00
FYI: Reports of this longstanding issue are piling up on Steam workshop page, most recently:

> can you tell me where to find the solution for cars disappearing on new road, improved road, destroyed and rebuilt road and public transport lines please

As a random guess, TMPE is likely listening or detouring stuff related to network create, delete, upgrade, etc., so that it can keep it's internal traffic metrics stuff up-to-date and remove any related customisations and so on. In doing so, is it failing to trigger events (or some other stuff) that vanilla does?

**Comment by krzychu124** [comment] 2019-02-18 16:30
Thanks, I will try to find where is the problem. It's hard to debug that. :-/

**Comment by krzychu124** [comment] 2019-02-19 14:09
I have hard time with reproducing this issue... Sometimes I can see similar situation than yours but sometimes no matter what am I doing I can't provoke vehicles to despawn... 

I can see that after road upgrade paths disappearing from path visualizer and sometimes ends just before upgraded segment but when vehicles approach this new end of path their status flag is changed to WaitingPath, their path is recalculated and they continue travel using upgraded segment.

I've had one issue after upgrading segments. Vehicles stopped just before upgraded segment and they won't move.  I've noticed that they don't have path rendered in Path Visualizer view at all or their path stopped at point just before updated segment. ModTools shows that their m_path id was constantly changing and when their block counter hits 100 they were despawned... I tried to debug that and those vehicles constantly invalidates every path created for them. I couldn't reproduce that case after creating second new game with the same settings and similar road configuration

With regards to removing segment, vehicles are despawned only if there is no path to their destination e.g. if you delete segment before and behind vehicle, it will despawn.

Path recalculation can lag because in general when you disable Advanced Vehicle AI their path seems to be recalculated only when they arrive to path end point (if you remove segment that can cause path cutting, only at this point vehicle will try to call for path recalculation)
Heavy trucks are excluded from Dynamic Lane Selection so even with enabled Advanced Vehicle AI they don't switch lanes and recalculate paths.

I still can't figure out if path is separated on parts when is calculated (to help DLS path change) or one time on just before vehicle spawn only.

I will try to check what part of code was changed since first report of this issue and compare current code to vanilla and after that disable redirection of some of methods

**Comment by aubergine10** [comment] 2019-02-19 14:42
I'm pretty  sure I had DLS turned off when I was testing, but will do another check.

There is also possibility that it's different mod that's causing the issue, so I will also try and do test with other mods disabled (especially some of the most likely ones, such as MOM, IPT2, DSL3, MoveIt, etc).

**Comment by krzychu124** [comment] 2019-02-19 20:44
While digging in code and testing I think I found why _Traffic Routes_ view is clearing paths after segment upgrade or removal.

Steps to show the problem:
1. open _Traffic Routes_ view
2. select any segment to visualize connected paths
3. close _Traffic Routes_ view
4. upgrade that previously selected segment
5. open again _Traffic Routes_ - no matter what segment you choose you won't see any route for a while.

I've checked vanilla and I see the same result.

__Explanation__ (_selected segment_ - last segment selected before closing Traffic Routes):
- when we are upgrading _selected road segment_ - __path will be cleared__ ( in the background we removing old and placing new in the same place (both segment nodes are persisted) 
- when we create new road in between start and end node of _selected segment_ - __path will be cleared__ (similar to upgrading but it creates node for junction with new segment and old segment is replaced with two new segments so in the background we placed 3 segments and 1 node) 
- when we create segment which is __not__ connected to _selected segment_ - __ paths via _selected segment_ will be still visible __, __BUT__ all paths which goes through touched segment will be wiped out.
- removing segment connected to other segment does not remove node in that segment - _ the other segments paths will be visible _
__Conclusions:__
- any modification to segment __Id__ (upgrade, splitting(connecting to), ?moving?(I didn't tested Move It)) will remove all paths which goes through that segment - currently only from _Traffic Routes_ view (_PathVisualizer_ class). 
Paths from _PathVisualizer_ must be related with pathfinder somehow because sometimes path ends just in front of upgraded segment and when vehicle approach that end it calls for path recalculation.

Now I have to check if that path from _Traffic Routes_ (_PathVisualizer_) is somehow related with path which was found for vehicle by pathfinder (maybe they sharing ID or something)

**Comment by aubergine10** [comment] 2019-02-19 21:42
I assume the traffic routes info view is just grabbing the path associated with vehicles (or iterating all vehicles to find any that cross selected segment). So if vehicle path breaks, so to does traffic route path.

**Comment by krzychu124** [comment] 2019-02-19 22:42
Yup, every path visible in Traffic Route is built from vehicles current path (m_path<PathUnit>) and next parts of full route are retrieved via  m_path.nextPathUnit until finished(?nexPathUnit == 0 or reached destination)

**Comment by krzychu124** [comment] 2019-02-19 23:06
If any mod override 
```NetManager::UpdateSegment(ushort lineID, ushort segmentID, ref NetSegment data)``` 
or
```NetManager::FinalizeSegment(ushort segment, ref NetSegment data)```
 our pathfinding logic will stop working due to segments collection desync.

**Comment by aubergine10** [comment] 2019-02-20 00:15
I think that was one of the key drivers to move to Harmony for patching. Apparently it has something that detects if something else has changed same stuff.

**Comment by krzychu124** [comment] 2019-02-20 05:56
Yes and theoretically both patches can run one after another depends on priority.

BTW yesterday I've been testing that harmony branch and it seems that it's working.
I didn't check yet if all methods has been moved to harmony patcher but I haven't found any issue with it (no null pointers, arrays out of bounds etc.). 
That branch is a little bit outdated and lacks few commits related to industry update but on the other hand it has a few classes which were moved to appropriate manager classes to increase code consistency and readability.

I think I could update it with latest stuff if I'll find some time to put it to test on heavily modded games :wink: 
I think that might solve our problems with those type of errors.

**Comment by aubergine10** [comment] 2019-02-22 17:08
In #101, some code changes have been tested to overcome issues of vehicles reaching a dead-end (allow them to choose any outgoing lane from the dead-end node)...

Upon further testing, it seems it might fix (or certainly improve) this #86 issue as well.

```
                bool isStockUturnPoint = (nextNode.m_flags & (NetNode.Flags.End | NetNode.Flags.OneWayOut)) != NetNode.Flags.None;

                bool relaxedLaneRouting =
                    m_isRoadVehicle &&
                    ((!m_queueItem.spawned || (m_queueItem.vehicleType & (ExtVehicleType.PublicTransport | ExtVehicleType.Emergency)) != ExtVehicleType.None) &&
                    (laneTransitions[k].laneId == m_startLaneA || laneTransitions[k].laneId == m_startLaneB)) || isStockUturnPoint;
```

**Comment by krzychu124** [comment] 2019-02-22 17:09
Great!

**Comment by aubergine10** [comment] 2019-02-22 22:47
Just done some more testing with a few different road layouts and road sizes:

* Vehicles are turning and repathing successfully at a dead-end caused by road bulldozing
* If a bulldozed segment is replaced, vehicles start using it within a few seconds (like vanilla)
* If a road is upgraded, vehicles continue using it

So, I think that minor bit of code (thanks @pcfantasy) seems to have solved the problem - I'm guessing some problem with u-turns at dead-ends was causing repathing to fail which was causing despawning.

Note: I'm building with ```master``` branch; I've not checked to see if there are other changes in there since the initial testing I did for this issue.

**Comment by krzychu124** [comment] 2019-02-22 22:48
Looks like it's working for me

**Comment by aubergine10** [comment] 2019-02-22 23:12
If you've added to a branch, you might as well send in PR :)

If we can get the incompatible mod checking done (even basic version - we can enhance later if needs be) I think it would be good time to push another release to steam.

**Comment by krzychu124** [comment] 2019-02-22 23:17
I've created very simple checking two days ago. I will make PR and you will see if it's worth push it to 1.10.16
I have to cleanup my mess first 😉

**Closed** 2019-02-22 23:49 UTC
Labels: bug, high priority, in-progress
