### ISSUE TITLE
Show notification if one specific traffic light of a timed light never changes to green

### ISSUE THREAD

**Issue by VictorPhilipp** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#134] opened 2019-03-03 03:29 UTC
https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/36

**Comment by VictorPhilipp** [comment] 2019-03-03 03:29
See also: #143

**Comment by aubergine10** [comment] 2019-03-03 05:06
Duplicate of #8

**Closed by aubergine10** 2019-03-03 05:06 UTC
Labels: duplicate, enhancement
