### ISSUE TITLE
"Green arrow" at timed traffic light junctions

### ISSUE THREAD

**Issue by VictorPhilipp** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#133] opened 2019-03-03 03:27 UTC
@patrickjpeterson

https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Gr%C3%BCner_Pfeil.jpg/220px-Gr%C3%BCner_Pfeil.jpg

https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/31

**Comment by VictorPhilipp** [comment] 2019-03-03 03:28
http://steamcommunity.com/workshop/filedetails/discussion/583429740/1470840994968932782/

**Comment by VictorPhilipp** [comment] 2019-03-03 03:28
We can already do that manually by separating right turn lights and make them always green.
In my eyes it should not be a "separate feature", maybe just a convenience function, to speed up the setup.

**Comment by VictorPhilipp** [comment] 2019-03-03 03:28
Not quite. The green arrow is like a Stop sign for right turns. You habe to stop first, then obey yield rules and only then you are allowed to turn right at a red traffic light.

**Comment by aubergine10** [comment] 2019-03-03 05:07
Duplicate of #46

**Closed by aubergine10** 2019-03-03 05:07 UTC
Labels: duplicate, feature
