### ISSUE TITLE
Bus routes: Pathfinding ignores 1-way directions in bus terminals

### ISSUE THREAD

**Issue by VictorPhilipp** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#204] opened 2019-03-03 05:18 UTC
Example assets that exhibit the problem:

* https://steamcommunity.com/sharedfiles/filedetails/?id=922683980&searchtext=
* https://steamcommunity.com/sharedfiles/filedetails/?id=868718614&searchtext=
* https://steamcommunity.com/sharedfiles/filedetails/?id=534580194&searchtext=

All those assets have 1-way networks inside them, but when creating a bus route it seems to treat the networks as bidirectional. This completely wrecks the concept of bus terminal buildings.

https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/230

**Comment by aubergine10** [comment] 2019-03-03 06:25
Duplicate of #10

**Closed by aubergine10** 2019-03-03 06:25 UTC
Labels: duplicate
