### ISSUE TITLE
Automatic timed traffic light step setup

### ISSUE THREAD

**Issue by VictorPhilipp** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#131] opened 2019-03-03 03:24 UTC
The step sequence of a timed traffic light can be created automatically based on the lane arrows that are present at the corresponding junction. The algorithm has first to find compatible traffic light states (green/red) and then build steps that incorporate these.
https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/28

**Comment by aubergine10** [comment] 2019-03-03 05:08
Duplicate of #5

**Closed by aubergine10** 2019-03-03 05:08 UTC
Labels: duplicate, feature
