### ISSUE TITLE
Lane connector cannot be used to make U-turns on medium/large roads with monorail

### ISSUE THREAD

**Issue by aditya-murda** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#293] opened 2019-04-21 04:35 UTC
Lane connector cannot be used to make U-turns on medium and large roads with monorail. This applies to stock and workshop assets. The outgoing connector does not appear on the opposite side of the road. I'm not sure whether it is not rendered or just simply does not allow to enable U-turns

edit: details

**Comment by FireController1847** [comment] 2019-04-21 04:40
Can you please go into a little more detail?

What happens? Does the outgoing connector dissapear? Is there no rendered outgoing connector? Does it just not let you select it?

If possible, please upload a video or some images of the issue happening.

**Comment by aditya-murda** [comment] 2019-04-21 04:48
My apologies. I edited the description. I'm attaching some screenshots
![20190421114137_1](https://user-images.githubusercontent.com/5810375/56465631-6016f780-642b-11e9-9118-0d9439180639.jpg)
![20190421114732_1](https://user-images.githubusercontent.com/5810375/56465632-60af8e00-642b-11e9-9be2-60d09cdb58bc.jpg)

**Comment by FireController1847** [comment] 2019-04-21 05:43
@aditya-murda Thanks for your report! I've confirmed this is and issue and it will be fixed at some point.

**Comment by aubergine10** [comment] 2019-04-21 14:41
We can probably get this fixed as part of #282 in time for v10.20 release.

**Comment by aubergine10** [comment] 2019-04-21 16:10
![monoturn](https://user-images.githubusercontent.com/1386719/56472595-3c1ddb00-6458-11e9-8fee-6080c2c9c44b.jpg)

Looks like lane connector treats the monorail track as the innermost lane, in which case the 'innermost _road_ lane' would not be considered a candidate for u-turn. So monorail lanes need ignoring when determining innermost road lane.

**Closed** 2020-02-16 08:10 UTC
Labels: BUG, LABS, LANE ROUTING, STABLE, confirmed, low priority

**Comment by aubergine10** [comment] 2020-02-19 05:53
This will be fixed in v11.1.1 :)
