### ISSUE TITLE
Default speed limits should be saved generally to the XML

### ISSUE THREAD

**Issue by VictorPhilipp** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#202] opened 2019-03-03 05:13 UTC
Please, don't have these settings also saved to the game save, it's a real bummer to set up the values when many road types (and tracks as well) are downloaded. 
When a player decides to have specific values, then the consideration is high that when starting a new game the same values are still to be considered.  
  
So please let these values be saved to either the TMPE_GlobalConfig.xml or to a custom XML, so players also can have a backup of their settings.

**Comment by VictorPhilipp** [comment] 2019-03-03 05:13
Would this also apply to custom roads which are not included in the vanilla game (such as the NExt2 roads)?

**Comment by VictorPhilipp** [comment] 2019-03-03 05:13
i would also see it as a global configuration. once you went through all the roads, you don't want to do it for every save again. also i don't think that ppl play with different speed limits on different maps .. i could be wrong though. could be an option or so.

**Comment by VictorPhilipp** [comment] 2019-03-03 05:13
@Xyrhenix this is the point - the more custom roads you got, the more (dozens or hundreds) of repeated similar clicking you can avoid if this would be a global setting.

**Comment by VictorPhilipp** [comment] 2019-03-03 05:13
@DaEgi01 if someone wants to have different settings in another game, create a backup of the XML and edit the values in there.

**Comment by VictorPhilipp** [comment] 2019-03-03 05:13
With regards to whether or not people would use this per-map, I can see situations where one might intentionally want different defaults per map (leading example being if someone has a map designed to replicate an American city and then one to replicate a British city).

If the intent for this feature request is for it to work with all roads (including modded roads), I would suggest a separate XML file because its length could vary considerably depending on how many roads are installed and actively used. In that could potentially be something like this:
```XML
<road>
    <name>ROAD_NAME</name>
    <speedlimit>50</speedlimit>
</road>
```

As an idea for implementation: In the default limit editor, have an additional button that's something like "Set global default". This would handle per-road global default setting. In the mod settings panel would then be "Set all global defaults to this save's," which would iterate through all the currently installed roads and write their default speed limits in the currently-loaded save to the global limits XML.

**Comment by VictorPhilipp** [comment] 2019-03-03 05:13
Since it's actually stated in the options that all the options are save specific, to save people getting confused about this 1 setting that's global, what about an export / import feature instead? Get all your road speeds set, export to a file, then for each new save you can quickly just import your speed file. This would also allow you to have multiple different speed files for different games. You could have one file that just sets all roads to 100 speed units for total madness, one with sensible speeds, one for country specific speeds, and you just import the speed set you want based on the game you intend to play.

**Comment by VictorPhilipp** [comment] 2019-03-03 05:13
I support that.

**Comment by VictorPhilipp** [comment] 2019-03-03 05:13
"Save settings as default for new games" button would be most desirable!

**Comment by VictorPhilipp** [comment] 2019-03-03 05:13
Tagging https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/issues/84

**Comment by aubergine10** [comment] 2019-03-03 05:14
Duplicate of #84

**Closed by aubergine10** 2019-03-03 05:14 UTC
Labels: duplicate, enhancement
