### ISSUE TITLE
Mod compatibility checker - null issue

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#386] opened 2019-06-20 13:13 UTC
Subaru had this error on the mods incompatibility checker (LABS prior to PR #333) - only happened one time, I'm unable to reproduce it.

However, I'll add some try/catch wrappers to the updates in #333 so future errors won't impact end-users.

Note: Mac platform - Mac has known issues with Linq, we should avoid Linq wherever possible. I'll try and rip out the Linq code from #333 - it's only used in one place IIRC, a `.last()` somewhere.

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Argument cannot be null.
Parameter name: source
  at System.Linq.Check.Source (System.Object source) [0x00000] in <filename unknown>:0 
  at System.Linq.Enumerable.ToArray[PublishedFileId] (IEnumerable`1 source) [0x00000] in <filename unknown>:0 
  at TrafficManager.Util.ModsCompatibilityChecker.GetUserModsList () [0x00000] in <filename unknown>:0 
  at TrafficManager.Util.ModsCompatibilityChecker..ctor () [0x00000] in <filename unknown>:0 
  at TrafficManager.TrafficManagerMod.OnGameIntroLoaded () [0x00000] in <filename unknown>:0 
  at TrafficManager.TrafficManagerMod.OnEnabled () [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (object,object[],System.Exception
```

**Comment by aubergine10** [comment] 2019-06-20 13:38
Log file containing the error: 
[Mac - Player.log](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3310654/Mac.-.Move.It.Procedural.Objects.log)

**Comment by dymanoid** [comment] 2019-06-20 15:38
It's not an issue with Linq.

Just `ContentManagerPanel.subscribedItemsTable` was `null`.

**Comment by dymanoid** [comment] 2019-06-20 15:44
@aubergine10, just curios: "Mac has known issues with Linq". Please provide some links proving that. As far as I know, there are no issues with Linq implementation in Mono, neither on Mac nor on any other supported platform.

**Comment by krzychu124** [comment] 2019-06-20 18:39
> Just ContentManagerPanel.subscribedItemsTable was null

@dymanoid, Is it possible? Just curious. I can see that` ContentManagerPanel` implements `MenuPanel` which calls `Initialize()` (init subscribedItemsTable array and other stuff) in `Start()` method.

I will check that anyway 😉 

BTW I would like to see more info about issues with Linq too. 
In case of checking for incompatible I didn't care much about performance because it is one time check and with 500k items, that operation should take max ~1sec (BTW Workshop has only ~186k items :smile: ).

**Comment by aubergine10** [comment] 2019-06-20 19:12
@dymanoid It was something @VictorPhilipp mentioned ages ago, specifically that it caused major performance issues on Macs (from very vague memory it was used in the savegame serialisation code).

In any case, I'll add the null checking on that `subscribedItemsTable` (I think I already ditched that in #333 so probably not an issue any more, but will check when time permits).

**Comment by dymanoid** [comment] 2019-06-20 20:07
I'm not sure the "massive performance issues" on Mac were caused by Linq. Rather by an inappropriate Linq usage 😄

@VictorPhilipp, can you give a particular example where Linq causes performance drop on Mac only? This is a very interesting topic.

@krzychu124, that field indeed can be null. The call into your code comes from `Awake` of the `OptionsMainPanel`. The `ContentManagerPanel` is a different object, thus it will be initialized independently from the options panel. The initialization order is not guaranteed.

**Comment by aubergine10** [comment] 2019-06-20 22:03
@krzychu124 Check the code in #333 - that scenario should no longer be an issue as it no longer pulls mod list from or otherwise interacts with the `ContentManagerPanel`.

**Closed** 2019-06-30 22:23 UTC
Labels: bug, irreproducible, technical
