### ISSUE TITLE
Cargoload of trains/trucks

### ISSUE THREAD

**Issue by VictorPhilipp** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#161] opened 2019-03-03 04:12 UTC
- Fix that cargo trains drive with around with really low loads of cargo. (1 - 30 %)
- Automatically select appropriate vehicle for load --> a van for a small load, a truck for a large load. (i've made difference in capacity in AVO, sadly i get trucks loaded for 50%, instead of a van, loaded for 100%), while vans would probably mean faster delivery.

https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/123

**Comment by aubergine10** [comment] 2019-03-03 04:34
Duplicate of #170

**Comment by aubergine10** [comment] 2019-04-04 20:20
Closing this as duplicate of 170

**Closed by aubergine10** 2019-04-04 20:20 UTC
Labels: discussion, feature, low priority
